#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Manage other monitors when lapton lid is open/close
## Edit according to your setup

LID="`ls /proc/acpi/button/lid | head -n1`"

if grep -q open /proc/acpi/button/lid/${LID}/state; then
    swaymsg output eDP-1 enable
else
    swaymsg output eDP-1 disable
fi
