#!/usr/bin/env bash

## launch terminal with alt config

CONFIG="$HOME/.config/sway/kitty/kitty.conf"

if [ "$1" == "-f" ]; then
	kitty --class='kitty-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
  kitty --class='kitty-full' --config="$CONFIG"
elif [ "$1" == "-s" ]; then
	kitty --class='kitty-float' --config="$CONFIG" \
	--window-size-pixels=$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2 -f "%wx%h")
else
  kitty --config="$CONFIG"
fi
