{
  inputs,
  config,
  pkgs,
  lib,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    inputs.expert-ls.packages.${pkgs.stdenv.hostPlatform.system}.default
    inputs.noctalia.packages.${pkgs.stdenv.hostPlatform.system}.default
    bat
    bear
    caligula
    clamav
    clamtk
    direnv
    evince
    eza
    file-roller
    ffmpeg-full
    fzf
    ghostty
    google-chrome
    git
    git-lfs
    gphoto2
    gpu-screen-recorder
    jq
    killall
    libnotify
    libqalculate
    lm_sensors
    mpv
    neovim
    nixfmt
    nixfmt-tree
    opencode
    eslint
    nss.tools
    pciutils
    pulseaudio
    playerctl
    python3
    quickshell
    kdePackages.skanpage
    swayimg
    tldr
    traceroute
    tailscale
    unzip
    usbutils
    v4l-utils
    vivaldi
    vivaldi-ffmpeg-codecs
    vlc
    vulkan-tools
    wget
    wl-clipboard
    xwayland-satellite
    zmk-studio
  ];

  environment.shells = with pkgs; [
    bashInteractive
    zsh
  ];

  # System-wide shell needs to be enabled
  programs.zsh.enable = true;
}
